NOTEBOOK_COLLECTION = "notebooks"

MAX_NOTEBOOK_TITLE = 150

MAX_NOTEBOOK_DESCRIPTION = 2000

DEFAULT_VISIBILITY = "private"

MAX_CELL_SOURCE_LENGTH = 100000

SUPPORTED_CELL_TYPES = (
    "markdown",
    "code",
)